package com.medical.manager.product.web.model;

public class TblBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_brand.NO
     *
     * @mbggenerated
     */
    private Long no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_brand.BRAND_NAME
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_brand.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_brand.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_brand.NO
     *
     * @return the value of tbl_brand.NO
     *
     * @mbggenerated
     */
    public Long getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_brand.NO
     *
     * @param no the value for tbl_brand.NO
     *
     * @mbggenerated
     */
    public void setNo(Long no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_brand.BRAND_NAME
     *
     * @return the value of tbl_brand.BRAND_NAME
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_brand.BRAND_NAME
     *
     * @param brandName the value for tbl_brand.BRAND_NAME
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_brand.REMARK
     *
     * @return the value of tbl_brand.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_brand.REMARK
     *
     * @param remark the value for tbl_brand.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_brand.CREATE_TIME
     *
     * @return the value of tbl_brand.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_brand.CREATE_TIME
     *
     * @param createTime the value for tbl_brand.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
    
}