package com.medical.manager.product.web.model;

public class TblDeliverProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.ORDER_NUMBER
     *
     * @mbggenerated
     */
    private Long orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.PRODUCT_NO
     *
     * @mbggenerated
     */
    private Long productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.NUMBER
     *
     * @mbggenerated
     */
    private Long number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private Long phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.DELIVER_REMARK
     *
     * @mbggenerated
     */
    private String deliverRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.EXPRESS
     *
     * @mbggenerated
     */
    private String express;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.EXPRESS_NO
     *
     * @mbggenerated
     */
    private Long expressNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_deliver_product.DELIVER_TIME
     *
     * @mbggenerated
     */
    private String deliverTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.ID
     *
     * @return the value of tbl_deliver_product.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.ID
     *
     * @param id the value for tbl_deliver_product.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.ORDER_NUMBER
     *
     * @return the value of tbl_deliver_product.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public Long getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.ORDER_NUMBER
     *
     * @param orderNumber the value for tbl_deliver_product.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public void setOrderNumber(Long orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.USER_NAME
     *
     * @return the value of tbl_deliver_product.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.USER_NAME
     *
     * @param userName the value for tbl_deliver_product.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.PRODUCT_NO
     *
     * @return the value of tbl_deliver_product.PRODUCT_NO
     *
     * @mbggenerated
     */
    public Long getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.PRODUCT_NO
     *
     * @param productNo the value for tbl_deliver_product.PRODUCT_NO
     *
     * @mbggenerated
     */
    public void setProductNo(Long productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.NUMBER
     *
     * @return the value of tbl_deliver_product.NUMBER
     *
     * @mbggenerated
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.NUMBER
     *
     * @param number the value for tbl_deliver_product.NUMBER
     *
     * @mbggenerated
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.PHONE_NUMBER
     *
     * @return the value of tbl_deliver_product.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public Long getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.PHONE_NUMBER
     *
     * @param phoneNumber the value for tbl_deliver_product.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.DELIVER_REMARK
     *
     * @return the value of tbl_deliver_product.DELIVER_REMARK
     *
     * @mbggenerated
     */
    public String getDeliverRemark() {
        return deliverRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.DELIVER_REMARK
     *
     * @param deliverRemark the value for tbl_deliver_product.DELIVER_REMARK
     *
     * @mbggenerated
     */
    public void setDeliverRemark(String deliverRemark) {
        this.deliverRemark = deliverRemark == null ? null : deliverRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.EXPRESS
     *
     * @return the value of tbl_deliver_product.EXPRESS
     *
     * @mbggenerated
     */
    public String getExpress() {
        return express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.EXPRESS
     *
     * @param express the value for tbl_deliver_product.EXPRESS
     *
     * @mbggenerated
     */
    public void setExpress(String express) {
        this.express = express == null ? null : express.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.EXPRESS_NO
     *
     * @return the value of tbl_deliver_product.EXPRESS_NO
     *
     * @mbggenerated
     */
    public Long getExpressNo() {
        return expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.EXPRESS_NO
     *
     * @param expressNo the value for tbl_deliver_product.EXPRESS_NO
     *
     * @mbggenerated
     */
    public void setExpressNo(Long expressNo) {
        this.expressNo = expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_deliver_product.DELIVER_TIME
     *
     * @return the value of tbl_deliver_product.DELIVER_TIME
     *
     * @mbggenerated
     */
    public String getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_deliver_product.DELIVER_TIME
     *
     * @param deliverTime the value for tbl_deliver_product.DELIVER_TIME
     *
     * @mbggenerated
     */
    public void setDeliverTime(String deliverTime) {
        this.deliverTime = deliverTime == null ? null : deliverTime.trim();
    }
}