package com.medical.manager.product.web.model;

public class TblMachineCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_machine_code.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_machine_code.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_machine_code.USE_STATUS
     *
     * @mbggenerated
     */
    private String useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_machine_code.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_machine_code.ID
     *
     * @return the value of tbl_machine_code.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_machine_code.ID
     *
     * @param id the value for tbl_machine_code.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_machine_code.CODE
     *
     * @return the value of tbl_machine_code.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_machine_code.CODE
     *
     * @param code the value for tbl_machine_code.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_machine_code.USE_STATUS
     *
     * @return the value of tbl_machine_code.USE_STATUS
     *
     * @mbggenerated
     */
    public String getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_machine_code.USE_STATUS
     *
     * @param useStatus the value for tbl_machine_code.USE_STATUS
     *
     * @mbggenerated
     */
    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus == null ? null : useStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_machine_code.CREATE_TIME
     *
     * @return the value of tbl_machine_code.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_machine_code.CREATE_TIME
     *
     * @param createTime the value for tbl_machine_code.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}