package com.medical.manager.product.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.medical.manager.product.web.model.TblProduct;
import com.medical.manager.product.web.query.TblProductExample;

@Repository("tblProductDao")
public interface ITblProductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int countByExample(TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int deleteByExample(TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int insert(TblProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int insertSelective(TblProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    List<TblProduct> selectByExampleWithBLOBs(TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    List<TblProduct> selectByExample(TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    TblProduct selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblProduct record, @Param("example") TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TblProduct record, @Param("example") TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblProduct record, @Param("example") TblProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TblProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblProduct record);
}