package com.medical.manager.product.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.medical.manager.product.web.model.TblOrder;
import com.medical.manager.product.web.query.TblOrderExample;

@Repository("tblOrderDao")
public interface ITblOrderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int countByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int deleteByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int insert(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int insertSelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    List<TblOrder> selectByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    TblOrder selectByPrimaryKey(Long orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblOrder record);
}