package com.medical.manager.product.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.medical.manager.product.web.model.TblMachineUse;
import com.medical.manager.product.web.query.TblMachineUseExample;

@Repository("tblMachineUseDao")
public interface ITblMachineUseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int countByExample(TblMachineUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int deleteByExample(TblMachineUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int insert(TblMachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int insertSelective(TblMachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    List<TblMachineUse> selectByExample(TblMachineUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    TblMachineUse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMachineUse record, @Param("example") TblMachineUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMachineUse record, @Param("example") TblMachineUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblMachineUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_machine_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblMachineUse record);
}