package com.medical.manager.product.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.medical.manager.product.web.model.TblBrand;
import com.medical.manager.product.web.query.TblBrandExample;

@Repository("tblBrandDao")
public interface ITblBrandDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int countByExample(TblBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int deleteByExample(TblBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int insert(TblBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int insertSelective(TblBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    List<TblBrand> selectByExample(TblBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    TblBrand selectByPrimaryKey(Long no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBrand record, @Param("example") TblBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBrand record, @Param("example") TblBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBrand record);
}